### ISSUE TITLE
Not working for me. 

### ISSUE THREAD

**Issue by josephcslater** [rjslater2000/RyGames#2]
In [2]: rg.TicTacToe1Player
---------------------------------------------------------------------------
Out[2]: <module 'rygames.TicTacToe1Player' from '/Users/jslater/Documents/python-dev/RyGames/rygames/TicTacToe1Player.py'>

In [3]: rg.TicTacToe1Player()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-85b885dec868> in <module>()
----> 1 rg.TicTacToe1Player()

TypeError: 'module' object is not callable

In [4]: rg.TicTacToe1Player.play
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-99a5b3715421> in <module>()
----> 1 rg.TicTacToe1Player.play

AttributeError: module 'rygames.TicTacToe1Player' has no attribute 'play'

In [5]: rg.Hangman
Out[5]: <module 'rygames.Hangman' from '/Users/jslater/Documents/python-dev/RyGames/rygames/Hangman.py'>
```
In [6]: rg.Hangman()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-f3163ed9d952> in <module>()
----> 1 rg.Hangman()

TypeError: 'module' object is not callable

In [7]: rg.Warships()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3f7c135dfd1d> in <module>()
----> 1 rg.Warships()

TypeError: 'module' object is not callable

```

**Comment by rjslater2000** [comment]
Fixed the issue. Run games with rg.gameName() now
